# Generated by Django 4.1.6 on 2023-02-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2500)),
                ("author_name", models.CharField(max_length=2500)),
                ("binding", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=20)),
                ("link", models.CharField(max_length=2500)),
            ],
        ),
    ]
