# Generated by Django 2.1.15 on 2023-02-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField(max_length=20)),
                ('Author', models.CharField(max_length=5000)),
                ('Binding', models.CharField(max_length=5000)),
                ('Price', models.FloatField(max_length=300)),
                ('Link', models.URLField(max_length=5000)),
            ],
        ),
    ]
