# Generated by Django 2.1.15 on 2023-02-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleBookData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(),
        ),
    ]
