# Generated by Django 2.1.15 on 2023-02-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleBookData', '0002_auto_20230222_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Link',
            new_name='LinkUrl',
        ),
        migrations.AddField(
            model_name='book',
            name='Title',
            field=models.CharField(default='LinkUrl', max_length=5000),
            preserve_default=False,
        ),
    ]
