# Generated by Django 2.1.15 on 2023-02-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleBookData', '0003_auto_20230223_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Location',
            field=models.CharField(default='Location', max_length=5000),
            preserve_default=False,
        ),
    ]
