# Generated by Django 3.2.18 on 2023-04-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singleBookData', '0007_auto_20230402_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='singleBookData.book'),
        ),
    ]
