# Generated by Django 4.2 on 2023-04-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singleBookData", "0007_auto_20230402_1458 2"),
        ("singleBookData", "0008_alter_listing_isbn"),
        ("singleBookData", "0008_alter_listing_isbn 2"),
    ]

    operations = []
