# Generated by Django 3.2.18 on 2023-03-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksellersite',
            name='Address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_lines', models.CharField(max_length=5000)),
                ('city', models.CharField(max_length=5000)),
                ('state', models.CharField(max_length=5000)),
                ('zip_code', models.CharField(max_length=5000)),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.booksellersite')),
            ],
        ),
    ]
