# Generated by Django 3.2.18 on 2023-04-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='store_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='seller.booksellersite'),
        ),
    ]
